apiVersion: garden.io/v1
kind: Project
name: play-garden

defaultEnvironment: local

environments:
  - name: local
    defaultNamespace: garden-local

providers:
  - name: local-kubernetes
    environments:
      - local